//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OOPNET_WPFApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OOPNET_WPFApp.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odustani.
        /// </summary>
        public static string ButtonCancel {
            get {
                return ResourceManager.GetString("ButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        public static string ButtonClose {
            get {
                return ResourceManager.GetString("ButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrdi.
        /// </summary>
        public static string ButtonConfirm {
            get {
                return ResourceManager.GetString("ButtonConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omiljena reprezentacija.
        /// </summary>
        public static string FavoriteRepLabel {
            get {
                return ResourceManager.GetString("FavoriteRepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Učitavanje....
        /// </summary>
        public static string Loading_Loading {
            get {
                return ResourceManager.GetString("Loading_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WPF - Utakmice.
        /// </summary>
        public static string MainTitle {
            get {
                return ResourceManager.GetString("MainTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kapetan:.
        /// </summary>
        public static string MyPlayer_Captain {
            get {
                return ResourceManager.GetString("MyPlayer_Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj golova:.
        /// </summary>
        public static string MyPlayer_GoalCount {
            get {
                return ResourceManager.GetString("MyPlayer_GoalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime:.
        /// </summary>
        public static string MyPlayer_Name {
            get {
                return ResourceManager.GetString("MyPlayer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj:.
        /// </summary>
        public static string MyPlayer_Number {
            get {
                return ResourceManager.GetString("MyPlayer_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pozicija:.
        /// </summary>
        public static string MyPlayer_Position {
            get {
                return ResourceManager.GetString("MyPlayer_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pregled igrača.
        /// </summary>
        public static string MyPlayer_Title {
            get {
                return ResourceManager.GetString("MyPlayer_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj žutih karti:.
        /// </summary>
        public static string MyPlayer_YellowCount {
            get {
                return ResourceManager.GetString("MyPlayer_YellowCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suparnička reprezentacija.
        /// </summary>
        public static string OppositeRepLabel {
            get {
                return ResourceManager.GetString("OppositeRepLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NE.
        /// </summary>
        public static string OptionNo {
            get {
                return ResourceManager.GetString("OptionNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DA.
        /// </summary>
        public static string OptionYes {
            get {
                return ResourceManager.GetString("OptionYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prvenstvo.
        /// </summary>
        public static string Settings_Cupy {
            get {
                return ResourceManager.GetString("Settings_Cupy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezolucija.
        /// </summary>
        public static string Settings_Resolution {
            get {
                return ResourceManager.GetString("Settings_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string Settings_Title {
            get {
                return ResourceManager.GetString("Settings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postavke.
        /// </summary>
        public static string SettingsButton {
            get {
                return ResourceManager.GetString("SettingsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poraza:.
        /// </summary>
        public static string TeamInformation_GamesLost {
            get {
                return ResourceManager.GetString("TeamInformation_GamesLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Odigrano:.
        /// </summary>
        public static string TeamInformation_GamesPlayed {
            get {
                return ResourceManager.GetString("TeamInformation_GamesPlayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neodlučeno:.
        /// </summary>
        public static string TeamInformation_GamesUndecided {
            get {
                return ResourceManager.GetString("TeamInformation_GamesUndecided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pobjeda:.
        /// </summary>
        public static string TeamInformation_GamesWon {
            get {
                return ResourceManager.GetString("TeamInformation_GamesWon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj golova:.
        /// </summary>
        public static string TeamInformation_GoalCount {
            get {
                return ResourceManager.GetString("TeamInformation_GoalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Razlika golova:.
        /// </summary>
        public static string TeamInformation_GoalsDifference {
            get {
                return ResourceManager.GetString("TeamInformation_GoalsDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primljeno golova:.
        /// </summary>
        public static string TeamInformation_GoalsTakenCount {
            get {
                return ResourceManager.GetString("TeamInformation_GoalsTakenCount", resourceCulture);
            }
        }
    }
}
